<?php $state=$deliveryState; ?>
<div class="page-header"><div><h2><?= e($student['full_name']) ?></h2><p>ID interno #<?= e($student['id']) ?> · Responsável: <?= e($student['guardian_name']) ?></p></div><div class="actions"><a class="btn btn-secondary" href="<?= e(url('/alunos')) ?>">Voltar</a><?php if($student['active']): ?><a class="btn btn-primary" href="<?= e(url('/alunos/'.$student['id'].'/editar')) ?>">Editar</a><?php else: ?><span class="badge">Aluno arquivado</span><?php endif; ?></div></div>
<div class="grid four"><div class="stat-card"><span class="stat-label">Trabalhos registrados</span><strong class="stat-value"><?= e($state['works']) ?></strong></div><div class="stat-card"><span class="stat-label">Ciclos de 4 alcançados</span><strong class="stat-value"><?= e($state['earned_cycles']) ?></strong></div><div class="stat-card"><span class="stat-label">Entregas realizadas</span><strong class="stat-value"><?= e($state['delivered_cycles']) ?></strong></div><div class="stat-card"><span class="stat-label">Entregas pendentes</span><strong class="stat-value"><?= e($state['pending_cycles']) ?></strong></div></div>
<?php if($state['pending_cycles']>0): ?><div class="delivery-alert"><strong>ENTREGAR PRODUÇÃO</strong><span><?= e($state['pending_cycles']) ?> ciclo(s) de quatro trabalhos aguardando entrega.</span></div><?php endif; ?>
<div class="grid two"><section class="panel"><div class="panel-header"><h3>Dados administrativos</h3></div><div class="panel-body"><p><strong>Responsável:</strong> <?= e($student['guardian_name']) ?></p><p><strong>Telefone do pai:</strong> <?= e($student['father_phone']?:'Não informado') ?></p><p><strong>Telefone da mãe:</strong> <?= e($student['mother_phone']?:'Não informado') ?></p><p><strong>Observações:</strong> <?= nl2br(e($student['notes']?:'Nenhuma')) ?></p><p><strong>Oficinas:</strong> <?= $workshops?e(implode(', ',array_column($workshops,'name'))):'Nenhuma' ?></p></div></section>
<section class="panel"><div class="panel-header"><h3>Registrar entrega</h3><p>Apenas produções disponíveis feitas por este aluno podem ser entregues.</p></div><div class="panel-body">
<?php if($student['active'] && $state['pending_cycles']>0 && $deliveryCandidates): ?><form class="form" method="POST" action="<?= e(url('/alunos/'.$student['id'].'/entregar')) ?>"><?= csrf_field() ?><div class="form-group"><label>Produção a entregar</label><select class="select" name="production_id" required><option value="">Selecione</option><?php foreach($deliveryCandidates as $p): ?><option value="<?= e($p['id']) ?>">Trabalho nº <?= e($p['work_number']) ?> — <?= e($p['product_name']) ?></option><?php endforeach; ?></select></div><div class="form-group"><label>Observação da entrega</label><input class="input" name="notes" placeholder="Opcional"></div><button class="btn btn-success">Marcar como entregue</button></form><?php elseif($state['pending_cycles']>0): ?><div class="empty">Há entrega pendente, mas não existe produção disponível deste aluno para entregar.</div><?php else: ?><div class="empty">Nenhuma entrega pendente neste momento.</div><?php endif; ?>
</div></section></div>
<section class="panel"><div class="panel-header"><h3>Histórico de produções</h3><p>O histórico nunca reinicia após uma entrega.</p></div><div class="panel-body">
<form method="GET" class="search-row"><select class="select" name="workshop_id"><option value="">Todas as oficinas</option><?php foreach($historyWorkshops as $w): ?><option value="<?= e($w['id']) ?>" <?= (string)$filterWorkshop===(string)$w['id']?'selected':'' ?>><?= e($w['name']) ?></option><?php endforeach; ?></select><button class="btn btn-secondary">Filtrar</button></form>
<div class="table-wrap"><table class="table"><thead><tr><th>Trabalho</th><th>Data</th><th>Oficina</th><th>Produto</th><th>Descrição</th><th>Qtd.</th><th>Situação</th><th>Entrega</th></tr></thead><tbody><?php foreach($productions as $p): ?><tr><td><strong>nº <?= e($p['work_number']) ?></strong></td><td><?= e(date('d/m/Y',strtotime($p['produced_at']))) ?></td><td><?= e($p['workshop_name']) ?></td><td><?= e($p['product_name']) ?></td><td><?= e($p['description']) ?></td><td><?= e($p['quantity']) ?></td><td><?= $p['delivery_id']?'<span class="badge badge-success">Entregue</span>':($p['availability_status']==='disponivel'?'<span class="badge badge-success">Disponível</span>':'<span class="badge">Indisponível</span>') ?></td><td><?= $p['delivery_id']?'<span class="badge badge-success">Entregue em '.e(date('d/m/Y',strtotime($p['delivered_at']))).'</span>':'—' ?></td></tr><?php endforeach; ?><?php if(!$productions): ?><tr><td colspan="8">Nenhuma produção neste filtro.</td></tr><?php endif; ?></tbody></table></div></div></section>
