<?php
$production=$production??[]; $workshops=$workshops??[]; $products=$products??[]; $users=$users??[]; $students=$students??[];
$selectedProductId=$production['product_id']??''; $selectedWorkshopId=$production['workshop_id']??''; $selectedStudentId=$production['student_id']??''; $selectedResponsibleId=$production['responsible_user_id']??'';
$quantity=$production['quantity']??1; $producedAt=$production['produced_at']??date('Y-m-d'); $purpose=$production['purpose']??''; $description=$production['description']??''; $availability=$production['availability_status']??'disponivel';
?>
<div class="form-group"><label for="student_id">Criança / aluno que realizou o trabalho</label><select class="select" id="student_id" name="<?= !empty($production['student_id']) ? 'student_display' : 'student_id' ?>" <?= !empty($production['student_id']) ? 'disabled' : 'required' ?>><option value="">Selecione um aluno</option><?php foreach($students as $student): ?><option value="<?= e($student['id']) ?>" <?= (string)$selectedStudentId===(string)$student['id']?'selected':'' ?>><?= e($student['full_name']) ?> — ID #<?= e($student['id']) ?></option><?php endforeach; ?></select><?php if(!empty($production['student_id'])): ?><input type="hidden" name="student_id" value="<?= e($selectedStudentId) ?>"><small>O aluno fica fixo após o registro para preservar a sequência e o histórico.</small><?php endif; ?><?php if(!$students): ?><small style="color:var(--danger)">Cadastre um aluno antes de registrar uma nova produção.</small><?php endif; ?></div>
<div class="form-group"><label for="product_id">Produto produzido</label><select class="select" id="product_id" name="product_id" required><option value="">Selecione um produto</option><?php foreach($products as $product): ?><option value="<?= e($product['id']) ?>" <?= (string)$selectedProductId===(string)$product['id']?'selected':'' ?>><?= e($product['name']) ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label for="workshop_id">Oficina</label><select class="select" id="workshop_id" name="workshop_id" required><option value="">Selecione uma oficina</option><?php foreach($workshops as $workshop): ?><option value="<?= e($workshop['id']) ?>" <?= (string)$selectedWorkshopId===(string)$workshop['id']?'selected':'' ?>><?= e($workshop['name']) ?></option><?php endforeach; ?></select><small>O aluno precisa estar vinculado à oficina escolhida.</small></div>
<div class="grid two"><div class="form-group"><label for="quantity">Quantidade produzida</label><input class="input" type="number" id="quantity" name="quantity" min="1" value="<?= e($quantity) ?>" required></div><div class="form-group"><label for="produced_at">Data</label><input class="input" type="date" id="produced_at" name="produced_at" value="<?= e($producedAt) ?>" required></div></div>
<div class="form-group"><label for="availability_status">Situação para entrega</label><select class="select" id="availability_status" name="availability_status" required><option value="disponivel" <?= $availability==='disponivel'?'selected':'' ?>>Disponível</option><option value="indisponivel" <?= $availability==='indisponivel'?'selected':'' ?>>Indisponível</option></select><small>Somente uma produção disponível da própria criança poderá ser entregue a ela.</small></div>
<?php if(is_professor()): ?><div class="form-group"><label for="responsible_user_id">Usuário que registrou / acompanhou</label><select class="select" id="responsible_user_id" name="responsible_user_id"><option value="">Usuário logado</option><?php foreach($users as $u): ?><option value="<?= e($u['id']) ?>" <?= (string)$selectedResponsibleId===(string)$u['id']?'selected':'' ?>><?= e($u['name']) ?> — <?= e($u['role']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<div class="form-group"><label for="purpose">Finalidade</label><select class="select" id="purpose" name="purpose" required><option value="">Selecione</option><?php foreach(array_unique(array_merge([$purpose],['Venda beneficente','Exposição interna','Doação','Aprendizado em oficina','Feira da ONG','Decoração da instituição','Encomenda','Atividade pedagógica'])) as $opt): ?><option value="<?= e($opt) ?>" <?= $purpose===$opt?'selected':'' ?>><?= e($opt) ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label for="description">Descrição / observação</label><textarea class="textarea" id="description" name="description" minlength="10" required><?= e($description) ?></textarea><small>Informe o que foi feito. O número do trabalho é calculado automaticamente por aluno.</small></div>
